version: "3.1"
services:
  web:
    image: uddinmtm/phpmysql
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dummy_db
      DB_USER: userdb
      DB_PASSWORD: passdb
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pass
      MYSQL_DATABASE: dummy_db
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passdb
    ports:
      - "3306:3306"
